apiVersion: v1
kind: Namespace
metadata:
  name: openshift-gitops
  labels:
    platform.io/team: platrel
    platform.io/managed-by: kustomize
    openshift.io/cluster-monitoring: "true"
  annotations:
    argocd.argoproj.io/managed-by: openshift-gitops
    platform.io/description: >
      GitOps controller namespace. ApplicationSets and Argo CD instances
      for client workloads are deployed here per the openshift-gitops pattern.
